const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const binary=require('../build-tools/node_modules/@sparticuz/chromium');
fs.writeFileSync(path.resolve('es-solos/app/build-tools/browser/chromium'),require('zlib').brotliDecompressSync(fs.readFileSync(path.resolve('es-solos/app/build-tools/node_modules/@sparticuz/chromium/bin/chromium.br'))));fs.chmodSync(path.resolve('es-solos/app/build-tools/browser/chromium'),0o755);
(async()=>{const fontRoot=path.resolve('es-solos/app/build-tools/node_modules/@fontsource/noto-sans-tc');const server=http.createServer((req,res)=>{if(req.url==='/qa-font.css'){res.setHeader('Content-Type','text/css');res.end(fs.readFileSync(fontRoot+'/400.css','utf8')+fs.readFileSync(fontRoot+'/700.css','utf8'));return}if(req.url.startsWith('/files/')){res.setHeader('Content-Type','font/woff2');res.end(fs.readFileSync(fontRoot+req.url));return}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync('es-solos/app/tenyear-salon-P2.0.0.html','utf8').replace('</head>','<link rel="stylesheet" href="/qa-font.css"></head>'))});await new Promise(r=>server.listen(8767,'127.0.0.1',r));const browser=await chromium.launch({executablePath:path.resolve('es-solos/app/build-tools/browser/chromium'),args:binary.args,headless:true});let errors=[],dialogs=[];const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'zh-TW'});const p=await context.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',async d=>{dialogs.push(d.message());await d.accept()});const nav=async n=>{await p.locator('.main-nav nav').getByRole('button',{name:n,exact:true}).click();await p.mouse.move(800,20)};const modal=()=>p.getByRole('dialog');const fill=async(label,v)=>modal().getByLabel(label,{exact:true}).fill(String(v));const btn=async n=>modal().getByRole('button',{name:n,exact:true}).click();const db=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('es_solos_p2_database')));const noModal=()=>p.getByRole('dialog').waitFor({state:'hidden'});
try{
 await p.goto('http://127.0.0.1:8767/');await p.evaluate(()=>document.fonts.ready);await nav('人員');for(const name of ['阿刀','協助小林']){await p.getByRole('button',{name:'＋新增夥伴'}).click();await fill('姓名',name);await fill('底薪',10000);await fill('固定加給',500);await fill('固定津貼',200);await fill('全勤參考金額',1000);await btn('儲存人員');await noModal()}assert.equal((await db()).staff.length,2);console.log('PASS 人員新增與持久化');
 await nav('系統');await p.getByRole('button',{name:'＋新增服務'}).click();await fill('項目品名','質感染髮');await fill('售價／每件',2000);await fill('材料成本／每次',400);await modal().getByLabel('服務類別').selectOption('染髮');await fill('每次協助費 $',100);await btn('儲存項目');await noModal();
 await nav('庫存');await p.getByRole('button',{name:'＋新增商品'}).click();await fill('項目品名','居家洗髮精');await fill('售價／每件',600);await fill('參考成本／每件',200);await fill('期初庫存（不登記付款）',10);await fill('安全庫存',3);await fill('販賣毛利獎金 %',10);await btn('儲存項目');await noModal();console.log('PASS 服務與商品設定');
 await nav('顧客');for(const phone of ['0911111111','0922222222']){await p.getByRole('button',{name:'＋新增顧客'}).click();await fill('姓名','小雨');await fill('電話',phone);await btn('儲存顧客');await noModal()}console.log('PASS 同名顧客建立');
 await nav('開單');await p.getByRole('button',{name:'會員',exact:true}).click();await p.getByLabel('會員姓名或電話').fill('091111');await p.locator('.search-results button').click();await p.locator('.catalog-card').filter({hasText:'質感染髮'}).click();await p.getByRole('button',{name:'調整 質感染髮'}).click();const data=await db();await modal().getByLabel('協助夥伴').selectOption(data.staff[1].id);await btn('儲存調整');await noModal();await p.locator('.catalog-card').filter({hasText:'居家洗髮精'}).click();await p.getByLabel('收現金額').fill('3000');await p.getByText('業績與抽成試算',{exact:true}).click();await p.screenshot({path:'es-solos/app/tests/order-desktop.png',fullPage:true});await p.getByRole('button',{name:'確認結帳',exact:true}).click();await btn('確認收款並結帳');await p.getByRole('dialog',{name:'交易收據'}).waitFor();await btn('完成');await noModal();let d=await db();assert.equal(d.records[0].total,2600);assert.equal(d.records[0].virtual,2000);assert.equal(d.records[0].actual,1500);assert.equal(d.records[0].commission,750);assert.equal(d.products[0].stock,9);console.log('PASS 結帳750算例、會員連結、販賣扣庫存');
 await p.reload();await nav('顧客');const first=p.locator('.entity-card').filter({hasText:'0911111111'});assert.ok((await first.innerText()).includes('$2,600'));const second=p.locator('.entity-card').filter({hasText:'0922222222'});assert.ok((await second.innerText()).includes('$0'));await first.getByRole('button',{name:'編輯',exact:true}).click();await fill('姓名','小雨改名');await btn('儲存顧客');await noModal();await p.locator('.entity-card').filter({hasText:'0911111111'}).getByRole('button',{name:'消費紀錄'}).click();assert.ok((await modal().innerText()).includes('$2,600'));await btn('關閉視窗');await noModal();console.log('PASS 重新開啟、顧客改名及歷史連動');
 await nav('查單');await p.getByLabel('起始',{exact:true}).fill('2020-01-01');await p.getByLabel('結束',{exact:true}).fill('2020-01-31');assert.equal(await p.locator('.record-card').count(),0);await nav('報表');await p.screenshot({path:'es-solos/app/tests/report-desktop.png',fullPage:true});assert.ok((await p.locator('.report-body').innerText()).includes('$1,500'));console.log('PASS 查單日期與報表分類金額');
 await nav('庫存');await p.getByRole('button',{name:'進貨',exact:true}).click();await fill('數量（整件／次）',5);await fill('本批進貨單價',100);await fill('本次已付款（未付款填 0）',200);await btn('確認記錄');await noModal();await p.getByRole('button',{name:'領用／盤點',exact:true}).click();await fill('數量（整件／次）',3);await btn('確認記錄');await noModal();d=await db();assert.equal(d.products[0].stock,11);assert.equal(d.expenses.length,1);assert.equal(d.expenses[0].amount,200);await nav('支出');await p.getByText(/待付貨款（全部日期/).click();await p.getByRole('button',{name:'補登付款'}).click();await btn('確認儲存');await noModal();d=await db();assert.equal(d.expenses.reduce((s,e)=>s+e.amount,0),500);console.log('PASS 進貨、耗用與尾款不重複列支');
 await nav('報表');await p.getByRole('button',{name:'薪資表',exact:true}).click();await p.getByLabel('人員',{exact:true}).selectOption(d.staff[0].id);await p.getByRole('button',{name:'產生／重算草稿'}).click();await modal().waitFor();await modal().getByLabel('已核對本月底薪、全勤、加扣項與借支').check();await btn('儲存核對內容');await p.waitForTimeout(100);await btn('確認薪資條');await p.waitForTimeout(100);await p.screenshot({path:'es-solos/app/tests/payroll-desktop.png',fullPage:true});await btn('登記已付');await p.waitForTimeout(100);await btn('關閉視窗');await noModal();d=await db();assert.equal(d.payrolls[0].status,'paid');assert.equal(d.expenses.filter(e=>e.type==='薪資付款').length,1);console.log('PASS 薪資草稿、確認、已付與支出');
 await nav('系統');await p.getByRole('button',{name:'備份與還原',exact:true}).click();const downloadPromise=p.waitForEvent('download');await p.getByRole('button',{name:'下載完整備份 JSON'}).click();const dl=await downloadPromise;const backupPath=path.resolve('es-solos/app/tests/backup-test.json');await dl.saveAs(backupPath);const before=await db();await p.getByLabel('選擇本專案備份').setInputFiles({name:'foreign.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'TENYEAR_BACKUP',data:{...before,project:'V28'}}))});await p.getByText('不是本專案的備份，禁止混用其他 POS 資料',{exact:true}).waitFor();await p.getByLabel('選擇本專案備份').setInputFiles(backupPath);await p.getByRole('button',{name:'確認還原此備份'}).click();await p.waitForTimeout(400);d=await db();assert.equal(d.records[0].total,before.records[0].total);assert.deepEqual(d.products,before.products);assert.deepEqual(d.payrolls,before.payrolls);console.log('PASS 備份下載、跨專案拒絕、還原一致');
 for(const size of [{width:768,height:1024},{width:390,height:844}]){await p.setViewportSize(size);for(const name of ['開單','查單','報表','顧客','庫存','人員','支出','系統']){await nav(name);await p.waitForTimeout(80);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,name+'頁面水平溢出');if(['報表','庫存','支出'].includes(name))await p.screenshot({path:`es-solos/app/tests/${name}-${size.width}.png`,fullPage:true})}await nav('人員');await p.getByRole('button',{name:'＋新增夥伴'}).click();await modal().getByRole('button',{name:'儲存人員'}).scrollIntoViewIfNeeded();const box=await modal().boundingBox();assert.ok(box.x>=0&&box.x+box.width<=size.width+1&&box.height<=size.height);await p.screenshot({path:`es-solos/app/tests/modal-${size.width}.png`});await btn('關閉視窗');await noModal()}console.log('PASS 768平板與390手機八頁／長彈窗');
 assert.deepEqual(errors,[]);fs.writeFileSync('es-solos/app/tests/ui-result.json',JSON.stringify({status:'passed',errors,dialogs,viewports:['1440x1000','768x1024','390x844'],checks:11},null,2));console.log('ALL UI CHECKS PASSED',errors.length,'page errors');
}catch(e){console.error(e);console.log('DIALOGS',dialogs);await p.screenshot({path:'es-solos/app/tests/failure.png',fullPage:true});fs.writeFileSync('es-solos/app/tests/failure.txt',await p.locator('body').innerText());process.exitCode=1}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
