const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const binary=require('../build-tools/node_modules/@sparticuz/chromium');
fs.writeFileSync(path.resolve('es-solos/app/build-tools/browser/chromium'),require('zlib').brotliDecompressSync(fs.readFileSync(path.resolve('es-solos/app/build-tools/node_modules/@sparticuz/chromium/bin/chromium.br'))));fs.chmodSync(path.resolve('es-solos/app/build-tools/browser/chromium'),0o755);
(async()=>{const fontRoot=path.resolve('es-solos/app/build-tools/node_modules/@fontsource/noto-sans-tc');const server=http.createServer((req,res)=>{if(req.url==='/qa-font.css'){res.setHeader('Content-Type','text/css');res.end(fs.readFileSync(fontRoot+'/400.css','utf8')+fs.readFileSync(fontRoot+'/700.css','utf8'));return}if(req.url.startsWith('/files/')){res.setHeader('Content-Type','font/woff2');res.end(fs.readFileSync(fontRoot+req.url));return}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fs.readFileSync('es-solos/app/tenyear-salon-P2.0.0.html','utf8').replace('</head>','<link rel="stylesheet" href="/qa-font.css"></head>'))});await new Promise(r=>server.listen(8767,'127.0.0.1',r));const browser=await chromium.launch({executablePath:path.resolve('es-solos/app/build-tools/browser/chromium'),args:binary.args,headless:true});let errors=[],dialogs=[];const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'zh-TW'});const p=await context.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',async d=>{dialogs.push(d.message());await d.accept()});const nav=async n=>{await p.locator('.main-nav nav').getByRole('button',{name:n,exact:true}).click();await p.mouse.move(800,20)};const modal=()=>p.getByRole('dialog');const fill=async(label,v)=>modal().getByLabel(label,{exact:true}).fill(String(v));const btn=async n=>modal().getByRole('button',{name:n,exact:true}).click();const db=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('es_solos_p2_database')));const noModal=()=>p.getByRole('dialog').waitFor({state:'hidden'});
try{
 const C=await import(require('url').pathToFileURL(path.resolve('es-solos/app/source/core.mjs')));const seed=C.emptyDB();seed.staff=[{id:'s',name:'小刀',commissionType:'個別設定',commissionValue:50},{id:'a',name:'協助小雨',commissionType:'個別設定',commissionValue:50}];seed.customers=[{id:'c',name:'林小姐',phone:'0912345678',tags:[],staffId:'s',gender:'女生'}];seed.services=[{id:'v',name:'質感染髮',cat:'染髮',price:2000,cost:400,assistMode:'amount',assistValue:100}];
 await p.goto('http://127.0.0.1:8767/');await p.evaluate(d=>localStorage.setItem('es_solos_p2_database',JSON.stringify(d)),seed);await p.reload();await nav('顧客');await p.getByRole('button',{name:'預付儲值',exact:true}).click();await p.getByLabel('儲值會員').selectOption('c');await p.getByLabel('儲值金額',{exact:true}).fill('3000');await p.getByRole('button',{name:'核對儲值收款',exact:true}).click();await btn('確認儲值收款');await noModal();assert.equal(C.walletBalance(await db(),'c'),3000);console.log('PASS UI儲值收款3000');
 await p.getByRole('button',{name:'顧客資料',exact:true}).click();await p.getByRole('button',{name:'帶入開單',exact:true}).click();await p.locator('.catalog-card').filter({hasText:'質感染髮'}).click();await p.getByRole('button',{name:'調整 質感染髮'}).click();await modal().getByLabel('協助夥伴').selectOption('a');await btn('儲存調整');await p.getByLabel('本次儲值扣款').fill('1500');await p.getByLabel('收現金額',{exact:true}).fill('500');await p.reload();assert.equal(await p.getByLabel('本次儲值扣款').inputValue(),'1500');await p.getByRole('button',{name:'確認結帳',exact:true}).click();await btn('確認收款並結帳');assert((await modal().innerText()).includes('儲值扣款 $1,500'));await btn('完成');let d=await db();assert.equal(d.records[0].commission,750);assert.equal(d.records[0].externalPaid,500);assert.equal(C.walletBalance(d,'c'),1500);assert.equal(C.cashReport(d,C.today(),C.today()).income,3500);console.log('PASS UI草稿恢復、會員帶入、儲值1500＋現金500與收據');
 await nav('顧客');await p.getByRole('button',{name:'預付儲值',exact:true}).click();await p.getByLabel('儲值會員').selectOption('c');await p.getByRole('button',{name:'餘額退款',exact:true}).click();await p.getByLabel('退款金額').fill('600');await p.getByLabel('備註／退款原因').fill('退回未用餘額');await p.getByRole('button',{name:'核對餘額退款'}).click();await btn('確認餘額退款');await noModal();assert.equal(C.walletBalance(await db(),'c'),900);console.log('PASS UI未用餘額退款');
 await nav('查單');await p.getByRole('button',{name:'作廢',exact:true}).click();console.log('VOID MODAL',await modal().innerText());await modal().getByLabel('作廢原因').fill('驗收作廢');await btn('確認作廢');await noModal();d=await db();assert.equal(C.walletBalance(d,'c'),2400);assert.equal(C.cashReport(d,C.today(),C.today()).income,2400);C.validateDB(d);console.log('PASS UI帳單作廢退回本金、現金退款不重複');
 await nav('顧客');await p.getByRole('button',{name:'預付儲值',exact:true}).click();await p.getByLabel('儲值會員').selectOption('c');await p.getByRole('button',{name:'作廢此筆儲值'}).click();await modal().getByLabel('作廢儲值原因').fill('測试餘額不足');await btn('確認作廢儲值');assert(dialogs.at(-1).includes('餘額不足'));await btn('關閉視窗');await p.locator('.page-scroll').evaluate(n=>n.scrollTop=0);await p.mouse.move(1100,25);await p.waitForTimeout(750);await p.screenshot({path:'es-solos/app/tests/P2-wallet-desktop.png'});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'es-solos/app/tests/P2-wallet-mobile.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);console.log('PASS UI儲值作廢超額保護、手機排版');
 await nav('報表');await p.getByRole('button',{name:'損益試算',exact:true}).click();assert((await p.locator('body').innerText()).includes('管理用損益試算'));await p.setViewportSize({width:1440,height:1000});await p.mouse.move(1100,25);await p.waitForTimeout(900);await p.screenshot({path:'es-solos/app/tests/P2-profit.png'});const misaligned=await p.locator('.pearl-group').evaluateAll(ns=>ns.filter(n=>n.offsetWidth>0).map(n=>{const a=n.querySelector(':scope>button.active,:scope>button.selected'),b=n.querySelector(':scope>.pearl-slider');return a&&b?Math.max(Math.abs(a.offsetLeft-b.offsetLeft),Math.abs(a.offsetTop-b.offsetTop)):0}));assert(misaligned.every(x=>x<2),JSON.stringify(misaligned));assert.equal(Math.round((await p.locator('.main-nav').boundingBox()).width),112);console.log('PASS 底框對齊與側欄回縮');console.log('PASS UI損益試算');
 assert.deepEqual(errors,[]);console.log('ALL WALLET UI CHECKS PASSED');fs.writeFileSync('es-solos/app/tests/P2-wallet-ui-result.json',JSON.stringify({errors,dialogs,pass:true},null,2));
}catch(e){console.error(e);console.log('DIALOGS',dialogs);await p.screenshot({path:'es-solos/app/tests/wallet-failure.png'});process.exitCode=1}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
